package apotea;

/**
 * Created with IntelliJ IDEA.
 * User: Linus
 * Date: 2017-12-07
 * Time: 20:22
 * To change this template use File | Settings | File Templates.
 */
public class TestData {

    public String getExample(){

    return
            "<!DOCTYPE html>\n" +
                    "<html lang=\"sv\">\n" +
                    "<head>\n" +

                    "</head>\n" +
                    "\n" +
                    "<body style=\"margin:0; padding:0;\">\n" +
                    "\n" +
                    "\n" +

                    "<div id=\"search-products\">\n" +
                    "    <div class=\"products5\">    <ul>            <li class=\"separator\"></li>            <li class=\"\">                <div class=\"img center\">                    <a href=\"/natriumklorid-braun-1000-ml\">                        <img src=\"https://media.apotea.se/product-images/MS/natriumklorid-braun-1000-ml-0.jpg\" alt=\" Natriumklorid Braun 0,9 % 1000 ml\" />                    </a>                </div>                <div style=\"position: relative;\">                    <div class=\"price-tag\" onclick=\"document.location='/natriumklorid-braun-1000-ml'\">                            <a href=\"/natriumklorid-braun-1000-ml\"><span class=\"\">22 kr</span></a>                    </div>                    <div class=\"badges\">                                            </div>                </div>                " +
                    "<div class=\"product-info-list\" id=\"list-41754\">                    <div class=\"is-med-div\"></div>                    <div class=\"name\" style=\"overflow:hidden;\"><a href=\"/natriumklorid-braun-1000-ml\"> Natriumklorid Braun 0,9 % 1000 ml</a></div>                    <div class=\"list-box\">                                                        <div class=\"empty-price\">&nbsp;</div>                            <a href=\"/natriumklorid-braun-1000-ml\"><span class=\"btn btn-success btn-product-action btn-product-more-info\">MER INFO</span></a>                        <div style=\"clear:both;\"></div>                    </div>                </div>            </li>            " +
                    "<li class=\"\">                <div class=\"img center\">                    <a href=\"/acura-komprimerad-sugtablett-10-mg-21-st\">                        <img src=\"https://media.apotea.se/product-images/MS/4820-1.jpg\" alt=\"Acura, komprimerad sugtablett 10 mg 21 st\" />                    </a>                </div>                <div style=\"position: relative;\">                    <div class=\"price-tag\" onclick=\"document.location='/acura-komprimerad-sugtablett-10-mg-21-st'\">                            <a href=\"/acura-komprimerad-sugtablett-10-mg-21-st\"><span class=\"\">35 kr</span></a>                    </div>                    <div class=\"badges\">                                            </div>                </div>                <div class=\"product-info-list\" id=\"list-22818\">                    <div class=\"is-med-div\">L&#228;kemedel</div>                    <div class=\"name\" style=\"overflow:hidden;\"><a href=\"/acura-komprimerad-sugtablett-10-mg-21-st\">Acura, komprimerad sugtablett 10 mg 21 st</a></div>                    <div class=\"list-box\">                                                        <div class=\"empty-price\">&nbsp;</div>                            <a href=\"/acura-komprimerad-sugtablett-10-mg-21-st\"><span class=\"btn btn-success btn-product-action btn-product-more-info\">MER INFO</span></a>                        <div style=\"clear:both;\"></div>                    </div>                </div>            </li>            " +
                    "<li class=\"\">                <div class=\"img center\">                    <a href=\"/allegra-filmdragerad-tablett-120-mg-sanofi-aventis-ab-10-st\">                        <img src=\"https://media.apotea.se/product-images/MS/allegra-filmdragerad-tablett-120-mg-sanofi-aventis-ab-10-st-0.jpg\" alt=\"Allegra, filmdragerad tablett 120 mg sanofi-aventis AB 10 st\" />                    </a>                </div>                <div style=\"position: relative;\">                    <div class=\"price-tag\" onclick=\"document.location='/allegra-filmdragerad-tablett-120-mg-sanofi-aventis-ab-10-st'\">                            <a href=\"/allegra-filmdragerad-tablett-120-mg-sanofi-aventis-ab-10-st\"><span class=\"\">55 kr</span></a>                    </div>                    <div class=\"badges\">                                            </div>                </div>                <div class=\"product-info-list\" id=\"list-68818\">                    <div class=\"is-med-div\">L&#228;kemedel</div>                    <div class=\"name\" style=\"overflow:hidden;\"><a href=\"/allegra-filmdragerad-tablett-120-mg-sanofi-aventis-ab-10-st\">Allegra, filmdragerad tablett 120 mg sanofi-aventis AB 10 st</a></div>                    <div class=\"list-box\">                                                        <div class=\"empty-price\">&nbsp;</div>                                <span class=\"btn btn-success btn-product-action list-add\" data-price=\"55,00\" data-name=\"Allegra, filmdragerad tablett 120 mg sanofi-aventis AB 10 st\" data-sku=\"68818\" title=\"Lägg 1 st Allegra, filmdragerad tablett 120 mg sanofi-aventis AB 10 st i varukorgen\" data-added-text='I VARUKORG' data-adding-text='KÖP&nbsp;&nbsp;&lt;span class=&quot;glyphicon glyphicon-refresh glyphicon-refresh-animate&quot;&gt;&lt;/span&gt;'>KÖP</span>                        <div style=\"clear:both;\"></div>                    </div>                </div>            </li>            " +
                    "<li class=\"\">                <div class=\"img center\">                    <a href=\"/allegra-filmdragerad-tablett-120-mg-30-st\">                        <img src=\"https://media.apotea.se/product-images/MS/allegra-filmdragerad-tablett-120-mg-30-st-0.jpg\" alt=\"Allegra, filmdragerad tablett 120 mg sanofi-aventis AB 30 st\" />                    </a>                </div>                <div style=\"position: relative;\">                    <div class=\"price-tag\" onclick=\"document.location='/allegra-filmdragerad-tablett-120-mg-30-st'\">                            <a href=\"/allegra-filmdragerad-tablett-120-mg-30-st\"><span class=\"\">144 kr</span></a>                    </div>                    <div class=\"badges\">                                            </div>                </div>                <div class=\"product-info-list\" id=\"list-26731\">                    <div class=\"is-med-div\">L&#228;kemedel</div>                    <div class=\"name\" style=\"overflow:hidden;\"><a href=\"/allegra-filmdragerad-tablett-120-mg-30-st\">Allegra, filmdragerad tablett 120 mg sanofi-aventis AB 30 st</a></div>                    <div class=\"list-box\">                                                        <div class=\"empty-price\">&nbsp;</div>                                <span class=\"btn btn-success btn-product-action list-add\" data-price=\"144,00\" data-name=\"Allegra, filmdragerad tablett 120 mg sanofi-aventis AB 30 st\" data-sku=\"26731\" title=\"Lägg 1 st Allegra, filmdragerad tablett 120 mg sanofi-aventis AB 30 st i varukorgen\" data-added-text='I VARUKORG' data-adding-text='KÖP&nbsp;&nbsp;&lt;span class=&quot;glyphicon glyphicon-refresh glyphicon-refresh-animate&quot;&gt;&lt;/span&gt;'>KÖP</span>                        <div style=\"clear:both;\"></div>                    </div>                </div>            </li>            " +
                    "<li class=\"\">                <div class=\"img center\">                    <a href=\"/allergenius-cat-specialschampo-250-ml\">                        <img src=\"https://media.apotea.se/product-images/MS/allergenius-cat-specialschampo-250-ml-0.jpg\" alt=\"Allergenius Cat Specialschampo 250 ml\" />                    </a>                </div>                <div style=\"position: relative;\">                    <div class=\"price-tag\" onclick=\"document.location='/allergenius-cat-specialschampo-250-ml'\">                            <a href=\"/allergenius-cat-specialschampo-250-ml\"><span class=\"\">269 kr</span></a>                    </div>                    <div class=\"badges\">                                            </div>                </div>                <div class=\"product-info-list\" id=\"list-170586\">                    <div class=\"is-med-div\"></div>                    <div class=\"name\" style=\"overflow:hidden;\"><a href=\"/allergenius-cat-specialschampo-250-ml\">Allergenius Cat Specialschampo 250 ml</a></div>                    <div class=\"list-box\">                                                        <div class=\"list-price\">Ca-pris: 289 kr</div>                                <span class=\"btn btn-success btn-product-action list-add\" data-price=\"269,00\" data-name=\"Allergenius Cat Specialschampo 250 ml\" data-sku=\"170586\" title=\"Lägg 1 st Allergenius Cat Specialschampo 250 ml i varukorgen\" data-added-text='I VARUKORG' data-adding-text='KÖP&nbsp;&nbsp;&lt;span class=&quot;glyphicon glyphicon-refresh glyphicon-refresh-animate&quot;&gt;&lt;/span&gt;'>KÖP</span>                        <div style=\"clear:both;\"></div>                    </div>                </div>            </li>            <li class=\"separator\"></li>            " +
                    "<li class=\"\">                <div class=\"img center\">                    <a href=\"/allergenius-dog-specialbalsam-mousse-150-ml\">                        <img src=\"https://media.apotea.se/product-images/MS/allergenius-dog-specialbalsam-mousse-150-ml-0.jpg\" alt=\"Allergenius Dog Specialbalsam Mousse 150 ml\" />                    </a>                </div>                <div style=\"position: relative;\">                    <div class=\"price-tag\" onclick=\"document.location='/allergenius-dog-specialbalsam-mousse-150-ml'\">                            <a href=\"/allergenius-dog-specialbalsam-mousse-150-ml\"><span class=\"\">229 kr</span></a>                    </div>                    <div class=\"badges\">                                            </div>                </div>                <div class=\"product-info-list\" id=\"list-170588\">                    <div class=\"is-med-div\"></div>                    <div class=\"name\" style=\"overflow:hidden;\"><a href=\"/allergenius-dog-specialbalsam-mousse-150-ml\">Allergenius Dog Specialbalsam Mousse 150 ml</a></div>                    <div class=\"list-box\">                                                        <div class=\"list-price\">Ca-pris: 249 kr</div>                                <span class=\"btn btn-success btn-product-action list-add\" data-price=\"229,00\" data-name=\"Allergenius Dog Specialbalsam Mousse 150 ml\" data-sku=\"170588\" title=\"Lägg 1 st Allergenius Dog Specialbalsam Mousse 150 ml i varukorgen\" data-added-text='I VARUKORG' data-adding-text='KÖP&nbsp;&nbsp;&lt;span class=&quot;glyphicon glyphicon-refresh glyphicon-refresh-animate&quot;&gt;&lt;/span&gt;'>KÖP</span>                        <div style=\"clear:both;\"></div>                    </div>                </div>            </li>            \n" +
                    "</div>\n" +
                    "</body>\n" +
                    "</html>\n";
    }

}
